# ~/.config/starship.toml

# Insert a blank line between shell prompts
add_newline = true
scan_timeout = 1000

# Replace the "❯" symbol
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

# Configure directory path
[directory]
truncation_length = 0
truncate_to_repo = false

# Disable git commit hash
[git_commit]
disabled = true

# Disable git branch
[git_branch]
disabled = true

# Optimize git status
[git_status]
disabled = true

# Show hostname
[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold dimmed white"

# Disable the package module
[package]
disabled = true

# Disable cloud modules
[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

# Disable language modules as requested
[nodejs]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[c]
disabled = true

[java]
disabled = true
